# Generated by Django 4.2 on 2023-04-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_alter_user_bio_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_sites',
        ),
    ]
