# Generated by Django 4.2 on 2023-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
