# Generated by Django 4.2 on 2023-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swim_site',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='swim_site',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='swim_site',
            name='parking_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
